### ISSUE TITLE
Suppress debuggee output

### ISSUE THREAD

**Issue by ytnobody** [sys-cat/WebService-Azure-Search#7]
Just a nitpicking. :stuck_out_tongue_winking_eye: 
- https://github.com/sys-cat/WebService-Azure-Search/blob/master/lib/WebService/Azure/Search.pm#L15
- https://github.com/sys-cat/WebService-Azure-Search/blob/master/lib/WebService/Azure/Search.pm#L110

**Comment by sys-cat** [comment]
modify from #10 .
