### ISSUE TITLE
Simplify initialization of hashref member

### ISSUE THREAD

**Issue by ytnobody** [sys-cat/WebService-Azure-Search#9]
- https://github.com/sys-cat/WebService-Azure-Search/blob/master/lib/WebService/Azure/Search.pm#L27
- https://github.com/sys-cat/WebService-Azure-Search/blob/master/lib/WebService/Azure/Search.pm#L32
- https://github.com/sys-cat/WebService-Azure-Search/blob/master/lib/WebService/Azure/Search.pm#L37
- https://github.com/sys-cat/WebService-Azure-Search/blob/master/lib/WebService/Azure/Search.pm#L42

I think, these may be bunched. As following.

```
$self->{setting} = +{
    base => undef, 
    index => undef,
    api => undef,
    admin => undef,
};
```

**Comment by sys-cat** [comment]
modify initialize from #11 .
